auth:
  image: cesanta/docker_auth
  entrypoint: /start.sh
  ports:
    - "5001:5001"
  volumes:
    - "./auth/start.sh:/start.sh:ro"
    - "./auth/config:/config:ro" 
    - "./auth/logs:/logs:rw"
    - "./certs:/certs:ro"

registry:
  image: registry:2
  restart: always
  ports:
    - "5000:5000"
  volumes:
    - "./certs:/certs:ro"
    - "./registry/conf:/etc/docker/registry:ro"
    - "./registry/storage:/var/lib/registry:rw"
      

    
  
