# . See reference.yml for explanation for explanation of all options.
#
#  auth:
#    token:
#      realm: "https://127.0.0.1:5001/auth"
#      service: "Docker registry"
#      issuer: "Acme auth server"
#      rootcertbundle: "/path/to/server.pem"

server:
  addr: ":5001"
  certificate: "/certs/auth.crt"
  key: "/certs/auth.key"

token:
  issuer: "Acme auth server"  # Must match issuer in the Registry config.
  expiration: 900

# This is for access to the public namespace. Anyone may access this folder so long as they have access. 
users: 
  "": {} # this allows anonymous access to the server.
  "admin":
    password: "$2y$05$LO.vzwpWC5LZGqThvEfznu8qhb5SGqvBSWY1J3yZ4AxtMRZ3kN5jC"  # badmin
  
acl:
  # This will allow authenticated users to pull/push
  - match:
      account: /.+/
      name: "${account}/*"
    actions: ['*']
 
  - match: 
      account: ""
      name: "public/*"
    actions: ["pull"]
    comment: "Allow access to pull on public namespace"

  - match:
      name: "public/*"
    actions: ['*'] 
    comment: "Allow all logged in users to access the public namespace"

  # The user "serviceaccount" (from LDAP) may not perform any docker actions
  # like push or pull.
  - match: {account: "serviceaccount"}
    actions: []

ext_authz:
  command: "/config/fake_auth.sh"
