apiVersion: v1
kind: Service
metadata:
  labels:
    service.type: auth
  name: auth
spec:
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
  selector:
    service.type: auth
status:
  loadBalancer: {}
