apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service.type: authz_server
  name: authz
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service.type: authz_server
    spec:
      containers:
      - image: c3tp/authz_server
        name: authz
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
