apiVersion: v1
kind: Service
metadata:
  labels:
    service.type: authz_server
  name: authz
spec:
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
  selector:
    service.type: authz_server
