apiVersion: v1
kind: Service
metadata:
  labels:
    service.type: registry
  name: registry
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 443
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    service.type: registry
status:
  loadBalancer: {}
